# push-tmux 設定ファイル例
# このファイルを config.toml としてコピーして使用してください

[tmux]
# tmux ターゲット設定
# target_session = "current"  # 省略時はデバイス名と同じセッション名、または特定のセッション名を指定
# target_window = "first"     # 省略時は最初のウィンドウ（デフォルト）、または特定のウィンドウインデックスを指定
# target_pane = "first"       # 省略時は最初のペイン（デフォルト）、または特定のペインインデックスを指定

[device_mapping]
# デバイス名とtmuxターゲットのマッピング設定
# デバイス名をキーとして、対応するtmuxセッション/ウィンドウ/ペインを指定
# 
# 設定形式:
# 1. 文字列形式（セッションのみ指定）:
#    "device-name" = "session-name"
# 
# 2. テーブル形式（詳細指定）:
#    [device_mapping."device-name"]
#    session = "session-name"  # 必須
#    window = "0"              # 省略時は "first"
#    pane = "1"                # 省略時は "first"
# 
# 例:
# # シンプルな指定（セッションのみ）
# "project-a" = "dev-session"
# 
# # 詳細な指定
# [device_mapping."mobile-app"]
# session = "frontend"
# window = "2"
# pane = "0"
# 
# [device_mapping."1on1-ver2"]
# session = "work"
# window = "first"  # または省略（デフォルトは "first"）
# pane = "first"    # または省略（デフォルトは "first"）

[daemon]
# デーモンモード設定
reload_interval = 1.0                    # ファイル監視間隔（秒）
watch_files = ["config.toml", ".env"]    # 監視するファイルのリスト
ignore_patterns = [                      # 無視するファイルパターン
    "*.pyc",
    "__pycache__/*",
    ".git/*",
    "*.log"
]

[daemon.logging]
# ロギング設定
enable_reload_logs = true                # リロードログの有効化
log_file = ""                           # ログファイルパス（空文字で標準出力）
log_level = "INFO"                      # ログレベル（DEBUG, INFO, WARNING, ERROR）

[daemon.monitoring]
# 監視設定
cpu_threshold = 80.0                    # CPU使用率閾値（%）
memory_threshold = 500                  # メモリ使用量閾値（MB）
websocket_check = true                  # WebSocket接続確認
heartbeat_interval = 30                 # ハートビート間隔（秒）