#!/bin/bash
# push-tmux wrapper installer
# Installs the push-tmux wrapper script to a directory in PATH

set -e

# デフォルトのインストール先
DEFAULT_INSTALL_DIR="$HOME/.local/bin"
INSTALL_DIR="${1:-$DEFAULT_INSTALL_DIR}"
PUSH_TMUX_DIR="$(cd "$(dirname "$0")" && pwd)"

# ヘルプ表示
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    cat << EOF
Usage: $0 [INSTALL_DIR]

Install push-tmux wrapper script to make it available from any directory.

Arguments:
  INSTALL_DIR    Directory to install the wrapper (default: $DEFAULT_INSTALL_DIR)

Examples:
  $0                    # Install to $DEFAULT_INSTALL_DIR
  $0 /usr/local/bin     # Install to /usr/local/bin (may require sudo)
  $0 ~/.local/bin       # Install to ~/.local/bin

After installation, you can run 'push-tmux' from any directory.
EOF
    exit 0
fi

echo "🔧 Installing push-tmux wrapper..."
echo "📁 Project directory: $PUSH_TMUX_DIR"
echo "📦 Install directory: $INSTALL_DIR"

# インストールディレクトリが存在しない場合は作成
if [ ! -d "$INSTALL_DIR" ]; then
    echo "📂 Creating install directory: $INSTALL_DIR"
    mkdir -p "$INSTALL_DIR"
fi

# インストールディレクトリに書き込み権限があるかチェック
if [ ! -w "$INSTALL_DIR" ]; then
    echo "❌ Error: No write permission to $INSTALL_DIR" >&2
    echo "Try running with sudo or choose a different directory" >&2
    exit 1
fi

# ラッパースクリプトを作成
WRAPPER_PATH="$INSTALL_DIR/push-tmux"
cat > "$WRAPPER_PATH" << EOF
#!/bin/bash
# push-tmux wrapper - generated by install-wrapper.sh
# Project path: $PUSH_TMUX_DIR

PUSH_TMUX_DIR="$PUSH_TMUX_DIR"

# プロジェクトディレクトリが存在するかチェック
if [ ! -d "\$PUSH_TMUX_DIR" ]; then
    echo "Error: push-tmux directory not found at \$PUSH_TMUX_DIR" >&2
    echo "The project may have been moved or deleted" >&2
    exit 1
fi

# pyproject.tomlが存在するかチェック
if [ ! -f "\$PUSH_TMUX_DIR/pyproject.toml" ]; then
    echo "Error: \$PUSH_TMUX_DIR doesn't appear to be a push-tmux project" >&2
    echo "pyproject.toml not found" >&2
    exit 1
fi

# uvが利用可能かチェック
if ! command -v uv >/dev/null 2>&1; then
    echo "Error: uv is not installed" >&2
    echo "Please install uv: https://github.com/astral-sh/uv" >&2
    exit 1
fi

# プロジェクトディレクトリに移動して実行
cd "\$PUSH_TMUX_DIR" && exec uv run python -m push_tmux "\$@"
EOF

# 実行権限を付与
chmod +x "$WRAPPER_PATH"

echo "✅ push-tmux wrapper installed successfully!"
echo ""
echo "🎉 You can now run push-tmux from any directory:"
echo "   push-tmux --help"
echo "   push-tmux register"
echo "   push-tmux listen"
echo ""

# PATHにインストールディレクトリが含まれているかチェック
if ! echo "$PATH" | tr ':' '\n' | grep -q "^$INSTALL_DIR$"; then
    echo "⚠️  Warning: $INSTALL_DIR is not in your PATH"
    echo "   Add this line to your ~/.bashrc or ~/.zshrc:"
    echo "   export PATH=\"$INSTALL_DIR:\$PATH\""
    echo ""
fi

echo "🗑️  To uninstall, simply run: rm $WRAPPER_PATH"